apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}-app
  labels:
    app: {{ include "my-app.name" . }}
    chart: {{ include "my-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
  selector:
    app: {{ include "my-app.name" . }}
    release: {{ .Release.Name }}
