apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}-db
  labels:
    app: {{ include "my-app.name" . }}
    chart: {{ include "my-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.postgresql.servicePort }}
      targetPort: {{ .Values.postgresql.servicePort }}
  selector:
    app: {{ include "my-app.name" . }}
    release: {{ .Release.Name }}
